# Generated by Django 5.2.4 on 2025-07-17 07:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_conversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identification of message', primary_key=True, serialize=False)),
                ('message_body', models.TextField(help_text='Body of message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
